name: Site Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Deploy to AWS S3
      run: aws s3 sync ${{ github.workspace }}/_site/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --acl public-read --delete --cache-control max-age=604800
    - name: Purge cache - hale.dev
      uses: nathanvaughn/actions-cloudflare-purge@master
      if: success()
      with:
        cf_zone: ${{ secrets.CLOUDFLARE_ZONEID_HALEDEV }}
        cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
    - name: Purge cache - jameshale.net
      uses: nathanvaughn/actions-cloudflare-purge@master
      if: success()
      with:
        cf_zone: ${{ secrets.CLOUDFLARE_ZONEID_JAMESHALENET }}
        cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
    - name: Purge cache - jameshale.me
      uses: nathanvaughn/actions-cloudflare-purge@master
      if: success()
      with:
        cf_zone: ${{ secrets.CLOUDFLARE_ZONEID_JAMESHALEME }}
        cf_auth: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
